### ISSUE TITLE
Unclear what to fill in for $ovbackup

### ISSUE THREAD

**Issue by karloluiten** [voidloop/ovirt-bash-backup#1]
Hi @voidloop ! Your script looks very useful, I just have no idea what to fill in for the $ovbackup variable. UUID of the host doing the backup? and if so: how do I find that?
Thanks!

**Comment by voidloop** [comment]
Hi. This script is old and I don't know if it still works. But if you want try it, the $ovbackup is the virtual machine doing the backup (and runs this script).  You can find the VM ID through the oVirt Engine admin web page selecting your "ovbackup virtual machine" or via ovirt-shell. 

If you are interested in oVirt backup, I developed another version of the script (in Python) https://github.com/voidloop/ovirt-python-backup with the same operating principle, but differently from the previous one: this doesn't shut down the virtual machine before creating the snapshots.

I'm sorry if they are not well documented.

**Comment by karloluiten** [comment]
PR#1 adds this info to the current script :)
